const std = @import("std");

pub const SoundEvent = enum {
    item_use_on,
    hit,
    step,
    step_baby,
    fly,
    jump,
    jump_prevent,
    @"break",
    place,
    heavy_step,
    gallop,
    fall,
    hurt,
    hurt_baby,
    hurt_in_water,
    death,
    death_baby,
    death_in_water,
    death_to_zombie,
    ambient,
    ambient_baby,
    ambient_in_water,
    ambient_in_air,
    ambient_tame,
    ambient_pollinate,
    breathe,
    mad,
    boost,
    bow,
    squish_big,
    squish_small,
    fall_big,
    fall_small,
    splash,
    fizz,
    flap,
    swim,
    drink,
    drink_honey,
    drink_milk,
    eat,
    takeoff,
    shake,
    plop,
    land,
    saddle,
    armor,
    mob_armor_stand_place,
    add_chest,
    throw,
    attack,
    attack_nodamage,
    attack_strong,
    warn,
    shear,
    milk,
    thunder,
    explode,
    fire,
    ignite,
    fuse,
    stare,
    spawn,
    born,
    shoot,
    break_block,
    launch,
    blast,
    large_blast,
    twinkle,
    remedy,
    unfect,
    convert_to_drowned,
    levelup,
    bow_hit,
    bullet_hit,
    extinguish_fire,
    item_fizz,
    chest_open,
    chest_closed,
    shulkerbox_open,
    shulkerbox_closed,
    enderchest_open,
    enderchest_closed,
    power_on,
    power_off,
    attach,
    detach,
    deny,
    tripod,
    pop,
    drop_slot,
    note,
    thorns,
    piston_in,
    piston_out,
    portal,
    water,
    lava_pop,
    lava,
    beacon_activate,
    beacon_ambient,
    beacon_deactivate,
    beacon_power,
    conduit_activate,
    conduit_ambient,
    conduit_attack,
    conduit_deactivate,
    conduit_short,
    bubble_pop,
    bubble_up,
    bubble_upinside,
    bubble_down,
    bubble_downinside,
    burp,
    bucket_fill_water,
    bucket_empty_water,
    bucket_fill_lava,
    bucket_empty_lava,
    bucket_fill_fish,
    bucket_empty_fish,
    armor_equip_chain,
    armor_equip_diamond,
    armor_equip_elytra,
    armor_equip_generic,
    armor_equip_gold,
    armor_equip_iron,
    armor_equip_leather,
    armor_equip_netherite,
    record_13,
    record_cat,
    record_blocks,
    record_chirp,
    record_creator,
    record_creator_music_box,
    record_far,
    record_mall,
    record_mellohi,
    record_stal,
    record_strad,
    record_ward,
    record_11,
    record_wait,
    record_null,
    record_pigstep,
    record_precipice,
    record_relic,
    record_otherside,
    record_5,
    record_tears,
    record_lava_chicken,
    flop,
    elderguardian_curse,
    teleport,
    shulker_open,
    shulker_close,
    mob_warning,
    mob_warning_baby,
    haggle,
    haggle_yes,
    haggle_no,
    haggle_idle,
    disappeared,
    reappeared,
    chorusgrow,
    chorusdeath,
    glass,
    potion_brewed,
    cast_spell,
    prepare_attack,
    prepare_summon,
    prepare_wololo,
    fang,
    charge,
    camera_take_picture,
    leashknot_break,
    leashknot_place,
    growl,
    whine,
    pant,
    purr,
    purreow,
    death_min_volume,
    death_mid_volume,
    imitate_blaze,
    imitate_cave_spider,
    imitate_creeper,
    imitate_elder_guardian,
    imitate_ender_dragon,
    imitate_enderman,
    imitate_endermite,
    imitate_evocation_illager,
    imitate_ghast,
    imitate_husk,
    imitate_magma_cube,
    imitate_polar_bear,
    imitate_shulker,
    imitate_silverfish,
    imitate_skeleton,
    imitate_slime,
    imitate_spider,
    imitate_stray,
    imitate_vex,
    imitate_vindication_illager,
    imitate_witch,
    imitate_wither,
    imitate_wither_skeleton,
    imitate_wolf,
    imitate_zombie,
    imitate_zombie_pigman,
    imitate_zombie_villager,
    block_end_portal_frame_fill,
    block_end_portal_spawn,
    random_anvil_use,
    bottle_dragonbreath,
    balloonpop,
    sparkler_active,
    item_trident_hit,
    item_trident_hit_ground,
    item_trident_return,
    item_trident_riptide_1,
    item_trident_riptide_2,
    item_trident_riptide_3,
    item_trident_throw,
    item_trident_thunder,
    block_fletching_table_use,
    elemconstruct_open,
    icebomb_hit,
    lt_reaction_icebomb,
    lt_reaction_bleach,
    lt_reaction_epaste,
    lt_reaction_epaste2,
    lt_reaction_fertilizer,
    lt_reaction_fireball,
    lt_reaction_mgsalt,
    lt_reaction_miscfire,
    lt_reaction_fire,
    lt_reaction_miscexplosion,
    lt_reaction_miscmystical,
    lt_reaction_miscmystical2,
    lt_reaction_product,
    sparkler_use,
    glowstick_use,
    block_turtle_egg_break,
    block_turtle_egg_crack,
    block_turtle_egg_hatch,
    block_turtle_egg_attack,
    block_sniffer_egg_crack,
    block_sniffer_egg_hatch,
    block_frog_spawn_hatch,
    block_frog_spawn_break,
    swoop,
    presneeze,
    sneeze,
    scared,
    ambient_aggressive,
    ambient_worried,
    cant_breed,
    block_scaffolding_climb,
    block_bamboo_sapling_place,
    crossbow_loading_start,
    crossbow_loading_middle,
    crossbow_loading_end,
    crossbow_shoot,
    crossbow_quick_charge_start,
    crossbow_quick_charge_middle,
    crossbow_quick_charge_end,
    item_shield_block,
    portal_travel,
    item_book_put,
    block_grindstone_use,
    block_bell_hit,
    block_campfire_crackle,
    block_sweet_berry_bush_hurt,
    block_sweet_berry_bush_pick,
    block_stonecutter_use,
    block_cartography_table_use,
    block_composter_empty,
    block_composter_fill,
    block_composter_fill_success,
    block_composter_ready,
    roar,
    stun,
    block_barrel_open,
    block_barrel_close,
    raid_horn,
    ui_stonecutter_take_result,
    ui_cartography_table_take_result,
    ui_loom_take_result,
    block_smoker_smoke,
    block_blastfurnace_fire_crackle,
    block_smithing_table_use,
    block_loom_use,
    ambient_in_raid,
    screech,
    sleep,
    block_furnace_lit,
    convert_mooshroom,
    milk_suspiciously,
    celebrate,
    block_beehive_enter,
    block_beehive_exit,
    block_beehive_shear,
    block_beehive_work,
    block_beehive_drip,
    ambient_cave,
    angry,
    retreat,
    converted_to_zombified,
    step_lava,
    tempt,
    panic,
    admire,
    particle_soul_escape_quiet,
    particle_soul_escape_loud,
    respawn_anchor_charge,
    respawn_anchor_deplete,
    respawn_anchor_set_spawn,
    respawn_anchor_ambient,
    ambient_crimson_forest_mood,
    ambient_warped_forest_mood,
    ambient_soulsand_valley_mood,
    ambient_nether_wastes_mood,
    ambient_crimson_forest_additions,
    ambient_warped_forest_additions,
    ambient_soulsand_valley_additions,
    ambient_nether_wastes_additions,
    ambient_basalt_deltas_additions,
    ambient_crimson_forest_loop,
    ambient_warped_forest_loop,
    ambient_soulsand_valley_loop,
    ambient_nether_wastes_loop,
    ambient_basalt_deltas_loop,
    lodestone_compass_link_compass_to_lodestone,
    ambient_basalt_deltas_mood,
    power_on_sculk_sensor,
    power_off_sculk_sensor,
    smithing_table_use,
    lay_egg,
    lay_spawn,
    bucket_fill_powder_snow,
    bucket_empty_powder_snow,
    cauldron_drip_water_pointed_dripstone,
    cauldron_drip_lava_pointed_dripstone,
    tilt_down_big_dripleaf,
    tilt_up_big_dripleaf,
    drip_water_pointed_dripstone,
    pick_berries_cave_vines,
    drip_lava_pointed_dripstone,
    copper_wax_on,
    copper_wax_off,
    scrape,
    item_spyglass_use,
    item_spyglass_stop_using,
    chime_amethyst_block,
    mob_player_hurt_drown,
    mob_player_hurt_on_fire,
    mob_player_hurt_freeze,
    ambient_screamer,
    hurt_screamer,
    death_screamer,
    milk_screamer,
    jump_to_block,
    pre_ram,
    pre_ram_screamer,
    ram_impact,
    ram_impact_screamer,
    squid_ink_squirt,
    glow_squid_ink_squirt,
    convert_to_stray,
    cake_add_candle,
    extinguish_candle,
    ambient_candle,
    block_click,
    block_click_fail,
    block_sculk_catalyst_bloom,
    block_sculk_shrieker_shriek,
    nearby_close,
    nearby_closer,
    nearby_closest,
    agitated,
    listening,
    heartbeat,
    tongue,
    item_given,
    item_taken,
    item_thrown,
    irongolem_crack,
    irongolem_repair,
    horn_break,
    horn_call0,
    horn_call1,
    horn_call2,
    horn_call3,
    horn_call4,
    horn_call5,
    horn_call6,
    horn_call7,
    imitate_warden,
    listening_angry,
    sonic_boom,
    sonic_charge,
    convert_to_frog,
    block_sculk_spread,
    charge_sculk,
    block_sculk_sensor_place,
    block_sculk_shrieker_place,
    block_enchanting_table_use,
    bundle_drop_contents,
    bundle_insert,
    bundle_insert_fail,
    bundle_remove_one,
    step_sand,
    dash_ready,
    pressure_plate_click_off,
    pressure_plate_click_on,
    button_click_off,
    button_click_on,
    door_open,
    door_close,
    trapdoor_open,
    trapdoor_close,
    fence_gate_open,
    fence_gate_close,
    insert,
    pickup,
    insert_enchanted,
    pickup_enchanted,
    shatter_pot,
    break_pot,
    brush,
    brush_completed,
    block_sign_waxed_interact_fail,
    @"note.bass",
    pumpkin_carve,
    mob_husk_convert_to_zombie,
    mob_pig_death,
    mob_hoglin_converted_to_zombified,
    ambient_underwater_enter,
    ambient_underwater_exit,
    bottle_fill,
    bottle_empty,
    block_decorated_pot_insert,
    block_decorated_pot_insert_fail,
    crafter_craft,
    crafter_fail,
    crafter_disable_slot,
    block_copper_bulb_turn_on,
    block_copper_bulb_turn_off,
    breeze_wind_charge_burst,
    imitate_breeze,
    trial_spawner_open_shutter,
    trial_spawner_detect_player,
    trial_spawner_close_shutter,
    trial_spawner_spawn_mob,
    trial_spawner_eject_item,
    trial_spawner_ambient,
    mob_armadillo_brush,
    mob_armadillo_scute_drop,
    armor_equip_wolf,
    armor_unequip_wolf,
    reflect,
    vault_open_shutter,
    vault_close_shutter,
    vault_eject_item,
    vault_insert_item,
    vault_insert_item_fail,
    vault_ambient,
    vault_activate,
    vault_deactivate,
    hurt_reduced,
    wind_charge_burst,
    armor_break_wolf,
    armor_crack_wolf,
    armor_repair_wolf,
    mace_smash_air,
    mace_smash_ground,
    mace_heavy_smash_ground,
    trial_spawner_charge_activate,
    trial_spawner_ambient_ominous,
    apply_effect_bad_omen,
    apply_effect_raid_omen,
    apply_effect_trial_omen,
    ominous_item_spawner_spawn_item,
    ominous_bottle_end_use,
    ominous_item_spawner_spawn_item_begin,
    ominous_item_spawner_about_to_spawn_item,
    imitate_bogged,
    vault_reject_rewarded_player,
    imitate_drowned,
    sponge_absorb,
    imitate_creaking,
    block_creaking_heart_trail,
    creaking_heart_spawn,
    activate,
    deactivate,
    freeze,
    unfreeze,
    open,
    open_long,
    close,
    close_long,
    imitate_phantom,
    imitate_zoglin,
    imitate_guardian,
    imitate_ravager,
    imitate_pillager,
    place_in_water,
    state_change,
    imitate_happy_ghast,
    armor_unequip_generic,
    ambient_weather_the_end_light_flash,
    lead_leash,
    lead_unleash,
    lead_break,
    unsaddle,
    armor_equip_copper,
    place_item,
    single_swap,
    multi_swap,
    item_enchant_lunge1,
    item_enchant_lunge2,
    item_enchant_lunge3,
    attack_critical,
    item_spear_attack_hit,
    item_spear_attack_miss,
    item_wooden_spear_attack_hit,
    item_wooden_spear_attack_miss,
    imitate_parched,
    imitate_camel_husk,
    item_spear_use,
    item_wooden_spear_use,
    saddle_in_water,
    item_stone_spear_attack_hit,
    item_iron_spear_attack_hit,
    item_copper_spear_attack_hit,
    item_golden_spear_attack_hit,
    item_diamond_spear_attack_hit,
    item_netherite_spear_attack_hit,
    item_stone_spear_attack_miss,
    item_iron_spear_attack_miss,
    item_copper_spear_attack_miss,
    item_golden_spear_attack_miss,
    item_diamond_spear_attack_miss,
    item_netherite_spear_attack_miss,
    item_stone_spear_use,
    item_iron_spear_use,
    item_copper_spear_use,
    item_golden_spear_use,
    item_diamond_spear_use,
    item_netherite_spear_use,
    pause_growth,
    reset_growth,
    pushed_by_player,
    bounce,
    slime_landing,
    absorb_block,
    eject_block,
    geyser_eruption_start,
    geyser_eruption_active,
    record_bounce,
    bucket_fill_land_animal,
    bucket_empty_land_animal,
    geyser_continuous_eruption_start,
    geyser_continuous_eruption_active,
    undefined,

    pub fn asString(self: SoundEvent) []const u8 {
        return switch (self) {
            .item_use_on => "item.use.on",
            .drink_honey => "drink.honey",
            .drink_milk => "drink.milk",
            .mob_armor_stand_place => "mob.armor_stand.place",
            .attack_nodamage => "attack.nodamage",
            .attack_strong => "attack.strong",
            .break_block => "break.block",
            .large_blast => "large.blast",
            .convert_to_drowned => "convert_to_drowned",
            .chest_open => "chest.open",
            .chest_closed => "chest.closed",
            .shulkerbox_open => "shulkerbox.open",
            .shulkerbox_closed => "shulkerbox.closed",
            .enderchest_open => "enderchest.open",
            .enderchest_closed => "enderchest.closed",
            .power_on => "power.on",
            .power_off => "power.off",
            .drop_slot => "drop.slot",
            .piston_in => "piston.in",
            .piston_out => "piston.out",
            .lava_pop => "lava.pop",
            .beacon_activate => "beacon.activate",
            .beacon_ambient => "beacon.ambient",
            .beacon_deactivate => "beacon.deactivate",
            .beacon_power => "beacon.power",
            .conduit_activate => "conduit.activate",
            .conduit_ambient => "conduit.ambient",
            .conduit_attack => "conduit.attack",
            .conduit_deactivate => "conduit.deactivate",
            .conduit_short => "conduit.short",
            .bubble_pop => "bubble.pop",
            .bubble_up => "bubble.up",
            .bubble_upinside => "bubble.upinside",
            .bubble_down => "bubble.down",
            .bubble_downinside => "bubble.downinside",
            .bucket_fill_water => "bucket.fill.water",
            .bucket_empty_water => "bucket.empty.water",
            .bucket_fill_lava => "bucket.fill.lava",
            .bucket_empty_lava => "bucket.empty.lava",
            .bucket_fill_fish => "bucket.fill.fish",
            .bucket_empty_fish => "bucket.empty.fish",
            .armor_equip_chain => "armor.equip_chain",
            .armor_equip_diamond => "armor.equip_diamond",
            .armor_equip_elytra => "armor.equip_elytra",
            .armor_equip_generic => "armor.equip_generic",
            .armor_equip_gold => "armor.equip_gold",
            .armor_equip_iron => "armor.equip_iron",
            .armor_equip_leather => "armor.equip_leather",
            .armor_equip_netherite => "armor.equip_netherite",
            .record_13 => "record.13",
            .record_cat => "record.cat",
            .record_blocks => "record.blocks",
            .record_chirp => "record.chirp",
            .record_creator => "record.creator",
            .record_creator_music_box => "record.creator_music_box",
            .record_far => "record.far",
            .record_mall => "record.mall",
            .record_mellohi => "record.mellohi",
            .record_stal => "record.stal",
            .record_strad => "record.strad",
            .record_ward => "record.ward",
            .record_11 => "record.11",
            .record_wait => "record.wait",
            .record_null => "record.null",
            .record_pigstep => "record.pigstep",
            .record_precipice => "record.precipice",
            .record_relic => "record.relic",
            .record_otherside => "record.otherside",
            .record_5 => "record.5",
            .record_tears => "record.tears",
            .record_lava_chicken => "record.lava_chicken",
            .elderguardian_curse => "elderguardian.curse",
            .shulker_open => "shulker.open",
            .shulker_close => "shulker.close",
            .mob_warning => "mob.warning",
            .mob_warning_baby => "mob.warning.baby",
            .haggle_yes => "haggle.yes",
            .haggle_no => "haggle.no",
            .haggle_idle => "haggle.idle",
            .camera_take_picture => "camera.take_picture",
            .leashknot_break => "leashknot.break",
            .leashknot_place => "leashknot.place",
            .death_min_volume => "death.min.volume",
            .death_mid_volume => "death.mid.volume",
            .imitate_blaze => "imitate.blaze",
            .imitate_cave_spider => "imitate.cave_spider",
            .imitate_creeper => "imitate.creeper",
            .imitate_elder_guardian => "imitate.elder_guardian",
            .imitate_ender_dragon => "imitate.ender_dragon",
            .imitate_enderman => "imitate.enderman",
            .imitate_endermite => "imitate.endermite",
            .imitate_evocation_illager => "imitate.evocation_illager",
            .imitate_ghast => "imitate.ghast",
            .imitate_husk => "imitate.husk",
            .imitate_magma_cube => "imitate.magma_cube",
            .imitate_polar_bear => "imitate.polar_bear",
            .imitate_shulker => "imitate.shulker",
            .imitate_silverfish => "imitate.silverfish",
            .imitate_skeleton => "imitate.skeleton",
            .imitate_slime => "imitate.slime",
            .imitate_spider => "imitate.spider",
            .imitate_stray => "imitate.stray",
            .imitate_vex => "imitate.vex",
            .imitate_vindication_illager => "imitate.vindication_illager",
            .imitate_witch => "imitate.witch",
            .imitate_wither => "imitate.wither",
            .imitate_wither_skeleton => "imitate.wither_skeleton",
            .imitate_wolf => "imitate.wolf",
            .imitate_zombie => "imitate.zombie",
            .imitate_zombie_pigman => "imitate.zombie_pigman",
            .imitate_zombie_villager => "imitate.zombie_villager",
            .block_end_portal_frame_fill => "block.end_portal_frame.fill",
            .block_end_portal_spawn => "block.end_portal.spawn",
            .random_anvil_use => "random.anvil_use",
            .bottle_dragonbreath => "bottle.dragonbreath",
            .item_trident_hit => "item.trident.hit",
            .item_trident_hit_ground => "item.trident.hit_ground",
            .item_trident_return => "item.trident.return",
            .item_trident_riptide_1 => "item.trident.riptide_1",
            .item_trident_riptide_2 => "item.trident.riptide_2",
            .item_trident_riptide_3 => "item.trident.riptide_3",
            .item_trident_throw => "item.trident.throw",
            .item_trident_thunder => "item.trident.thunder",
            .block_fletching_table_use => "block.fletching_table.use",
            .lt_reaction_icebomb => "lt.reaction.icebomb",
            .lt_reaction_bleach => "lt.reaction.bleach",
            .lt_reaction_epaste => "lt.reaction.epaste",
            .lt_reaction_epaste2 => "lt.reaction.epaste2",
            .lt_reaction_fertilizer => "lt.reaction.fertilizer",
            .lt_reaction_fireball => "lt.reaction.fireball",
            .lt_reaction_mgsalt => "lt.reaction.mgsalt",
            .lt_reaction_miscfire => "lt.reaction.miscfire",
            .lt_reaction_fire => "lt.reaction.fire",
            .lt_reaction_miscexplosion => "lt.reaction.miscexplosion",
            .lt_reaction_miscmystical => "lt.reaction.miscmystical",
            .lt_reaction_miscmystical2 => "lt.reaction.miscmystical2",
            .lt_reaction_product => "lt.reaction.product",
            .block_turtle_egg_break => "block.turtle_egg.break",
            .block_turtle_egg_crack => "block.turtle_egg.crack",
            .block_turtle_egg_hatch => "block.turtle_egg.hatch",
            .block_turtle_egg_attack => "block.turtle_egg.attack",
            .block_sniffer_egg_crack => "block.sniffer_egg.crack",
            .block_sniffer_egg_hatch => "block.sniffer_egg.hatch",
            .block_frog_spawn_hatch => "block.frog_spawn.hatch",
            .block_frog_spawn_break => "block.frog_spawn.break",
            .ambient_aggressive => "ambient.aggressive",
            .ambient_worried => "ambient.worried",
            .block_scaffolding_climb => "block.scaffolding.climb",
            .block_bamboo_sapling_place => "block.bamboo_sapling.place",
            .crossbow_loading_start => "crossbow.loading.start",
            .crossbow_loading_middle => "crossbow.loading.middle",
            .crossbow_loading_end => "crossbow.loading.end",
            .crossbow_shoot => "crossbow.shoot",
            .crossbow_quick_charge_start => "crossbow.quick_charge.start",
            .crossbow_quick_charge_middle => "crossbow.quick_charge.middle",
            .crossbow_quick_charge_end => "crossbow.quick_charge.end",
            .item_shield_block,
            => "item.shield.block",
            .portal_travel => "portal.travel",
            .item_book_put => "item.book.put",
            .block_grindstone_use => "block.grindstone.use",
            .block_bell_hit => "block.bell.hit",
            .block_campfire_crackle => "block.campfire.crackle",
            .block_sweet_berry_bush_hurt => "block.sweet_berry_bush.hurt",
            .block_sweet_berry_bush_pick => "block.sweet_berry_bush.pick",
            .block_stonecutter_use => "block.stonecutter.use",
            .block_cartography_table_use => "block.cartography_table.use",
            .block_composter_empty => "block.composter.empty",
            .block_composter_fill => "block.composter.fill",
            .block_composter_fill_success => "block.composter.fill_success",
            .block_composter_ready => "block.composter.ready",
            .block_barrel_open => "block.barrel.open",
            .block_barrel_close => "block.barrel.close",
            .raid_horn => "raid.horn",
            .ui_stonecutter_take_result => "ui.stonecutter.take_result",
            .ui_cartography_table_take_result => "ui.cartography_table.take_result",
            .ui_loom_take_result => "ui.loom.take_result",
            .block_smoker_smoke => "block.smoker.smoke",
            .block_blastfurnace_fire_crackle => "block.blastfurnace.fire_crackle",
            .block_smithing_table_use => "block.smithing_table.use",
            .block_loom_use => "block.loom.use",
            .ambient_in_raid => "ambient.in.raid",
            .block_furnace_lit => "block.furnace.lit",
            .block_beehive_enter => "block.beehive.enter",
            .block_beehive_exit => "block.beehive.exit",
            .block_beehive_shear => "block.beehive.shear",
            .block_beehive_work => "block.beehive.work",
            .block_beehive_drip => "block.beehive.drip",
            .ambient_cave => "ambient.cave",
            .particle_soul_escape_quiet => "particle.soul_escape.quiet",
            .particle_soul_escape_loud => "particle.soul_escape.loud",
            .respawn_anchor_charge => "respawn_anchor.charge",
            .respawn_anchor_deplete => "respawn_anchor.deplete",
            .respawn_anchor_set_spawn => "respawn_anchor.set_spawn",
            .respawn_anchor_ambient => "respawn_anchor.ambient",
            .ambient_crimson_forest_mood => "ambient.crimson_forest.mood",
            .ambient_warped_forest_mood => "ambient.warped_forest.mood",
            .ambient_soulsand_valley_mood => "ambient.soulsand_valley.mood",
            .ambient_nether_wastes_mood => "ambient.nether_wastes.mood",
            .ambient_crimson_forest_additions => "ambient.crimson_forest.additions",
            .ambient_warped_forest_additions => "ambient.warped_forest.additions",
            .ambient_soulsand_valley_additions => "ambient.soulsand_valley.additions",
            .ambient_nether_wastes_additions => "ambient.nether_wastes.additions",
            .ambient_basalt_deltas_additions => "ambient.basalt_deltas.additions",
            .ambient_crimson_forest_loop => "ambient.crimson_forest.loop",
            .ambient_warped_forest_loop => "ambient.warped_forest.loop",
            .ambient_soulsand_valley_loop => "ambient.soulsand_valley.loop",
            .ambient_nether_wastes_loop => "ambient.nether_wastes.loop",
            .ambient_basalt_deltas_loop => "ambient.basalt_deltas.loop",
            .lodestone_compass_link_compass_to_lodestone => "lodestone_compass.link_compass_to_lodestone",
            .ambient_basalt_deltas_mood => "ambient.basalt_deltas.mood",
            .power_on_sculk_sensor => "power.on.sculk_sensor",
            .power_off_sculk_sensor => "power.off.sculk_sensor",
            .smithing_table_use => "smithing_table.use",
            .bucket_fill_powder_snow => "bucket.fill.powder_snow",
            .bucket_empty_powder_snow => "bucket.empty.powder_snow",
            .cauldron_drip_water_pointed_dripstone => "cauldron_drip.water.pointed_dripstone",
            .cauldron_drip_lava_pointed_dripstone => "cauldron_drip.lava.pointed_dripstone",
            .tilt_down_big_dripleaf => "tilt_down.big_dripleaf",
            .tilt_up_big_dripleaf => "tilt_up.big_dripleaf",
            .drip_water_pointed_dripstone => "drip.water.pointed_dripstone",
            .pick_berries_cave_vines => "pick_berries.cave_vines",
            .drip_lava_pointed_dripstone => "drip.lava.pointed_dripstone",
            .copper_wax_on => "copper.wax.on",
            .copper_wax_off => "copper.wax.off",
            .item_spyglass_use => "item.spyglass.use",
            .item_spyglass_stop_using => "item.spyglass.stop_using",
            .chime_amethyst_block => "chime.amethyst_block",
            .mob_player_hurt_drown => "mob.player.hurt_drown",
            .mob_player_hurt_on_fire => "mob.player.hurt_on_fire",
            .mob_player_hurt_freeze => "mob.player.hurt_freeze",
            .pre_ram_screamer => "pre_ram.screamer",
            .ram_impact_screamer => "ram_impact.screamer",
            .squid_ink_squirt => "squid.ink_squirt",
            .glow_squid_ink_squirt => "glow_squid.ink_squirt",
            .cake_add_candle => "cake.add_candle",
            .extinguish_candle => "extinguish.candle",
            .ambient_candle => "ambient.candle",
            .block_click => "block.click",
            .block_click_fail => "block.click.fail",
            .block_sculk_catalyst_bloom => "block.sculk_catalyst.bloom",
            .block_sculk_shrieker_shriek => "block.sculk_shrieker.shriek",
            .irongolem_crack => "irongolem.crack",
            .irongolem_repair => "irongolem.repair",
            .imitate_warden => "imitate.warden",
            .block_sculk_spread => "block.sculk.spread",
            .charge_sculk => "charge.sculk",
            .block_sculk_sensor_place => "block.sculk_sensor.place",
            .block_sculk_shrieker_place => "block.sculk_shrieker.place",
            .block_enchanting_table_use => "block.enchanting_table.use",
            .bundle_drop_contents => "bundle.drop_contents",
            .bundle_insert => "bundle.insert",
            .bundle_insert_fail => "bundle.insert_fail",
            .bundle_remove_one,
            => "bundle.remove_one",
            .pressure_plate_click_off => "pressure_plate.click_off",
            .pressure_plate_click_on => "pressure_plate.click_on",
            .button_click_off => "button.click_off",
            .button_click_on => "button.click_on",
            .door_open => "door.open",
            .door_close => "door.close",
            .trapdoor_open => "trapdoor.open",
            .trapdoor_close => "trapdoor.close",
            .fence_gate_open => "fence_gate.open",
            .fence_gate_close => "fence_gate.close",
            .block_sign_waxed_interact_fail => "block.sign.waxed_interact_fail",
            .@"note.bass" => "note.bass",
            .pumpkin_carve => "pumpkin.carve",
            .mob_husk_convert_to_zombie => "mob.husk.convert_to_zombie",
            .mob_pig_death => "mob.pig.death",
            .mob_hoglin_converted_to_zombified => "mob.hoglin.converted_to_zombified",
            .ambient_underwater_enter => "ambient.underwater.enter",
            .ambient_underwater_exit => "ambient.underwater.exit",
            .bottle_fill => "bottle.fill",
            .bottle_empty => "bottle.empty",
            .block_decorated_pot_insert => "block.decorated_pot.insert",
            .block_decorated_pot_insert_fail => "block.decorated_pot.insert_fail",
            .block_copper_bulb_turn_on => "block.copper_bulb.turn_on",
            .block_copper_bulb_turn_off => "block.copper_bulb.turn_off",
            .breeze_wind_charge_burst => "breeze_wind_charge.burst",
            .trial_spawner_open_shutter => "trial_spawner.open_shutter",
            .trial_spawner_detect_player => "trial_spawner.detect_player",
            .trial_spawner_close_shutter => "trial_spawner.close_shutter",
            .trial_spawner_spawn_mob => "trial_spawner.spawn_mob",
            .trial_spawner_eject_item => "trial_spawner.eject_item",
            .trial_spawner_ambient => "trial_spawner.ambient",
            .mob_armadillo_brush => "mob.armadillo.brush",
            .mob_armadillo_scute_drop => "mob.armadillo.scute_drop",
            .vault_open_shutter => "vault.open_shutter",
            .vault_close_shutter => "vault.close_shutter",
            .vault_eject_item => "vault.eject_item",
            .vault_insert_item => "vault.insert_item",
            .vault_insert_item_fail => "vault.insert_item_fail",
            .vault_ambient => "vault.ambient",
            .vault_activate => "vault.activate",
            .vault_deactivate => "vault.deactivate",
            .wind_charge_burst => "wind_charge.burst",
            .armor_break_wolf => "armor.break_wolf",
            .armor_crack_wolf => "armor.crack_wolf",
            .armor_repair_wolf => "armor.repair_wolf",
            .mace_smash_air => "mace.smash_air",
            .mace_smash_ground => "mace.smash_ground",
            .mace_heavy_smash_ground => "mace.heavy_smash_ground",
            .trial_spawner_charge_activate => "trial_spawner.charge_activate",
            .trial_spawner_ambient_ominous => "trial_spawner.ambient_ominous",
            .apply_effect_bad_omen => "apply_effect.bad_omen",
            .apply_effect_raid_omen => "apply_effect.raid_omen",
            .apply_effect_trial_omen => "apply_effect.trial_omen",
            .ominous_item_spawner_spawn_item => "ominous_item_spawner.spawn_item",
            .ominous_bottle_end_use => "ominous_bottle.end_use",
            .ominous_item_spawner_spawn_item_begin => "ominous_item_spawner.spawn_item_begin",
            .ominous_item_spawner_about_to_spawn_item => "ominous_item_spawner.about_to_spawn_item",
            .vault_reject_rewarded_player => "vault.reject_rewarded_player",
            .block_creaking_heart_trail => "block.creaking_heart.trail",
            .ambient_weather_the_end_light_flash => "ambient.weather.the_end_light_flash",
            .lead_leash => "lead.leash",
            .lead_unleash => "lead.unleash",
            .lead_break => "lead.break",
            .item_enchant_lunge1 => "item.enchant.lunge1",
            .item_enchant_lunge2 => "item.enchant.lunge2",
            .item_enchant_lunge3 => "item.enchant.lunge3",
            .item_spear_attack_hit => "item.spear.attack_hit",
            .item_spear_attack_miss => "item.spear.attack_miss",
            .item_wooden_spear_attack_hit => "item.wooden_spear.attack_hit",
            .item_wooden_spear_attack_miss => "item.wooden_spear.attack_miss",
            .item_spear_use => "item.spear.use",
            .item_wooden_spear_use => "item.wooden_spear.use",
            .item_stone_spear_attack_hit => "item.stone_spear.attack_hit",
            .item_iron_spear_attack_hit => "item.iron_spear.attack_hit",
            .item_copper_spear_attack_hit => "item.copper_spear.attack_hit",
            .item_golden_spear_attack_hit => "item.golden_spear.attack_hit",
            .item_diamond_spear_attack_hit => "item.diamond_spear.attack_hit",
            .item_netherite_spear_attack_hit => "item.netherite_spear.attack_hit",
            .item_stone_spear_attack_miss => "item.stone_spear.attack_miss",
            .item_iron_spear_attack_miss => "item.iron_spear.attack_miss",
            .item_copper_spear_attack_miss => "item.copper_spear.attack_miss",
            .item_golden_spear_attack_miss => "item.golden_spear.attack_miss",
            .item_diamond_spear_attack_miss => "item.diamond_spear.attack_miss",
            .item_netherite_spear_attack_miss => "item.netherite_spear.attack_miss",
            .item_stone_spear_use => "item.stone_spear.use",
            .item_iron_spear_use => "item.iron_spear.use",
            .item_copper_spear_use => "item.copper_spear.use",
            .item_golden_spear_use => "item.golden_spear.use",
            .item_diamond_spear_use => "item.diamond_spear.use",
            .item_netherite_spear_use => "item.netherite_spear.use",
            else => @tagName(self),
        };
    }

    pub fn fromString(id_str: []const u8) SoundEvent {
        inline for (std.meta.fields(SoundEvent)) |field| {
            const ev = @as(SoundEvent, @enumFromInt(field.value));
            if (std.mem.eql(u8, ev.asString(), id_str)) {
                return ev;
            }
        }
        return .undefined;
    }
};
