pub const StackRequestActionType = enum(u8) {
    Take = 0,
    Place = 1,
    Swap = 2,
    Drop = 3,
    Destroy = 4,
    Consume = 5,
    Create = 6,
    PlaceInContainer = 7,
    TakeOutContainer = 8,
    LabTableCombine = 9,
    BeaconPayment = 10,
    MineBlock = 11,
    CraftRecipe = 12,
    CraftRecipeAuto = 13,
    CraftCreative = 14,
    CraftRecipeOptional = 15,
    CraftGrindstone = 16,
    CraftLoom = 17,
    CraftNonImplementedDeprecated = 18,
    CraftResultsDeprecated = 19,
    _,
};
